### ISSUE TITLE
[BUG] Influxdb Cloud 2.x 

### ISSUE THREAD

**Issue by Bra1nsen** [influxdata/influxdb2-sample-data#17]
Already contacted Support:

![image](https://user-images.githubusercontent.com/58213050/203037861-0d72818c-c6e2-45c6-9aee-f6fef9aee5b7.png)

Problem:

**Set Data Saving to forever**
![image](https://user-images.githubusercontent.com/58213050/203038187-37859617-3425-4bd7-92ed-883fb27c34c1.png)

### UNABLE TO DOWNLOAD OLDER THAN 30 DAYS:
![image](https://user-images.githubusercontent.com/58213050/203038212-149f6524-fb18-491e-840d-a4fcac39b48d.png)

Please Help!

**Comment by sanderson** [comment]
@Bra1nsen You can set a custom time range in your notebook. In the time selection dropdown menu, **scroll up** and click **Custom Time Range**. You can then define whatever time range you want.

<img width="221" alt="image" src="https://user-images.githubusercontent.com/181484/203361583-f7ae37dd-dc41-4deb-8fd0-d1f9439440d6.png">

<img width="734" alt="image" src="https://user-images.githubusercontent.com/181484/203361685-b32dc2d1-bf0d-4c2a-900f-fdda9c9bd392.png">

**Comment by Bra1nsen** [comment]
Ohh my god THANK YOU
